version: '3.4'

services:
  counselor.platform.api:
    image: ${DOCKER_REGISTRY-}counselorplatformapi
    build:
      context: .
      dockerfile: src/Counselor.Platform.Api/Dockerfile
    ports:
      - "8080:8080"
      - "5432:5432"
    container_name: counselor-platform/api

  counselor.platform.worker:
    image: ${DOCKER_REGISTRY-}counselorplatformworker
    build:
      context: .
      dockerfile: src/Counselor.Platform.Worker/Dockerfile
    ports:
      - "32650:32650"
      - "5432:5432"
    container_name: counselor-platform/worker

  counselor.platform.client:
    image: ${DOCKER_REGISTRY-}counselorplatformclient
    build:
      context: .
      dockerfile: src/Counselor.Platform.Client/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    container_name: counselor-platform/client