version: '3.4'

x-common-environment: &common-environment
  Platform__Database__Server: "host.docker.internal"

name: counselor-platform
services:
  counselor.platform.worker:
    image: ${DOCKER_REGISTRY-}counselor-platform.worker
    build:
      context: .
      dockerfile: src/Counselor.Platform.Worker/Dockerfile
    environment:
      <<: *common-environment
    container_name: counselor-platform.worker

  counselor.platform.api:
    image: ${DOCKER_REGISTRY-}counselor-platform.api
    build:
      context: .
      dockerfile: src/Counselor.Platform.Api/Dockerfile
    ports:
      - 32600:80
      - 44345:443
    environment:
      <<: *common-environment
    container_name: counselor-platform.api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

  counselor.platform.client:
    image: ${DOCKER_REGISTRY-}counselor-platform.client
    build:
      context: .
      dockerfile: src/Counselor.Platform.Client/Dockerfile
    ports:
      - 32620:80
    container_name: counselor-platform.client
