version: "3"
services:
  worker:
    build:
    ports:
      - "32650:32650"    
    container_name: counselor-platform-worker
  api:
    build:
    ports:
      - "8080:8080"
    depends_on:
      - worker
    container_name: counselor-platform-api
  client:
    build:
    ports:
      - "80:80"
    depends_on:
      - api
    container_name: counselor-platform-client