version: "3"
services:
  worker:
    image: counselor/woker
    build:
      context: .
      dockerfile: src\Counselor.Platform.Worker\Dockerfile
    ports:
      - "32650:32650"
      - "5432:5432"
    container_name: counselor-platform-worker
  api:
    image: counselor/api
    build:
      context: .
      dockerfile: src\Counselor.Platform.Api\Dockerfile
    ports:
      - "8080:8080"
      - "5432:5432"
    depends_on:
      - worker
    container_name: counselor-platform-api
  client:
    image: counselor/client
    build:
      context: .
      dockerfile: src\Counselor.Platform.Client\Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    container_name: counselor-platform-client