Platform:
  DialogsPath: "Dialogs"
  Database:
    Server: localhost
    Port: 5432
    UserId: counselor
    Password: 
    Database: counselor.platform
Telegram:
  IsEnabled: true
  Token:
  SendErrorReport: false
  DialogName: Sample
Discord:
  IsEnabled: false
  Token:
  SendErrorReport: false
Cache:
  UserDataLifetime: 300