Platform:
  DialogsPath: "Dialogs"
  Database:
    Server: localhost
    Port: 5432
    UserId: counselor
    Password: 
    Database: counselor.platform
Cache:
  UserDataLifetime: 300
Service:
  ServiceIntervalMs: 60000
  DialogTTLMs: 300000
  Transports:
    - SystemName: Telegram
      IsEnabled: true
      SendErrorReport: false      
    - SystemName: Discord
      IsEnabled: false
      SendErrorReport: false